### ISSUE TITLE
error when trying to setup with !npcrsetup

### ISSUE THREAD

**Issue by thefaiint** [XxLMM13xXgaming/lmm_npc_robbing#1]
when i try to setup a robbing npc with !npcrsetup it just tells me

" Something went wrong! Make sure your id is something withno spaces like 'store1'!"

no matter what i do

i tried another skin , another name , another id everything.
just wont work for me

**Comment by thefaiint** [comment]
do you still work on this or is it pretty much dead now?

**Comment by XxLMM13xXgaming** [comment]
It's dead at the moment however if people really wish that I fix it I will
